In [8]:
import pandas as pd
import re

In [3]:
df = pd.read_csv(r"C:\Users\91882\Desktop\AI-Based Email Spam Detection\data\email_text.csv")
df['text'].iloc[0]

"me spam is the tool for dissident news since the fact that it's unsolicited means that recipients can't be blamed for being on a mailing list russell turpin that depends on how the list is collected or even on what the senders say about how the list is collected better to just put it on a website and that way it can be surfed anonymously and it doesn't clutter my inbox it doesn't work that way a website is opt in spam is no opt if you visit a samizdat site you can get in trouble if you get samizdat spam the worst that can be said is that you might have read it and as long as the mailers send to individuals who clearly didn't opt in like party officials then other recipients can't get in trouble for requesting the mail plus it's much harder to block spam than web sites but this shouldn't come as a surprize spam is speech it may be sleazy but so what lucas http xent com mailman listinfo fork"

## Converting to lowercase

In [4]:
df['clean_text'] = df['text'].str.lower()

In [5]:
df[['text','clean_text']].head()

,text,clean_text
0,me spam is the tool for dissident news since t...,me spam is the tool for dissident news since t...
1,escapenumber escapenumber escapenumber penguin...,escapenumber escapenumber escapenumber penguin...
2,on wednesday escapenumber july escapenumber es...,on wednesday escapenumber july escapenumber es...
3,can't think of how i'd be running afoul of th...,can't think of how i'd be running afoul of th...
4,forwarded by william knowles http www thesun c...,forwarded by william knowles http www thesun c...

## Removing HTML tags :

In [6]:
def remove_html(text):
    return re.sub(r'<.*?>', '', text)

In [9]:
df['clean_text'] = df['clean_text'].apply(remove_html)

In [12]:
df[['text', 'clean_text']].head()

,text,clean_text
0,me spam is the tool for dissident news since t...,me spam is the tool for dissident news since t...
1,escapenumber escapenumber escapenumber penguin...,escapenumber escapenumber escapenumber penguin...
2,on wednesday escapenumber july escapenumber es...,on wednesday escapenumber july escapenumber es...
3,can't think of how i'd be running afoul of th...,can't think of how i'd be running afoul of th...
4,forwarded by william knowles http www thesun c...,forwarded by william knowles http www thesun c...

In [17]:
print(df.loc[0,'clean_text'])

me spam is the tool for dissident news since the fact that it's unsolicited means that recipients can't be blamed for being on a mailing list russell turpin that depends on how the list is collected or even on what the senders say about how the list is collected better to just put it on a website and that way it can be surfed anonymously and it doesn't clutter my inbox it doesn't work that way a website is opt in spam is no opt if you visit a samizdat site you can get in trouble if you get samizdat spam the worst that can be said is that you might have read it and as long as the mailers send to individuals who clearly didn't opt in like party officials then other recipients can't get in trouble for requesting the mail plus it's much harder to block spam than web sites but this shouldn't come as a surprize spam is speech it may be sleazy but so what lucas http xent com mailman listinfo fork

In [18]:
print(df.loc[0,'text'])

me spam is the tool for dissident news since the fact that it's unsolicited means that recipients can't be blamed for being on a mailing list russell turpin that depends on how the list is collected or even on what the senders say about how the list is collected better to just put it on a website and that way it can be surfed anonymously and it doesn't clutter my inbox it doesn't work that way a website is opt in spam is no opt if you visit a samizdat site you can get in trouble if you get samizdat spam the worst that can be said is that you might have read it and as long as the mailers send to individuals who clearly didn't opt in like party officials then other recipients can't get in trouble for requesting the mail plus it's much harder to block spam than web sites but this shouldn't come as a surprize spam is speech it may be sleazy but so what lucas http xent com mailman listinfo fork

## Removing URLS :

In [19]:
def remove_urls(text):
    return re.sub(r'http\S+|www\S+', '', text)

In [20]:
df['clean_text'] = df['clean_text'].apply(remove_urls)

In [23]:
print(df.loc[0,'clean_text'])

me spam is the tool for dissident news since the fact that it's unsolicited means that recipients can't be blamed for being on a mailing list russell turpin that depends on how the list is collected or even on what the senders say about how the list is collected better to just put it on a website and that way it can be surfed anonymously and it doesn't clutter my inbox it doesn't work that way a website is opt in spam is no opt if you visit a samizdat site you can get in trouble if you get samizdat spam the worst that can be said is that you might have read it and as long as the mailers send to individuals who clearly didn't opt in like party officials then other recipients can't get in trouble for requesting the mail plus it's much harder to block spam than web sites but this shouldn't come as a surprize spam is speech it may be sleazy but so what lucas http xent com mailman listinfo fork

## Removing Special Characters :

In [24]:
def remove_special_chars(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

In [25]:
df['clean_text'] = df['clean_text'].apply(remove_special_chars)

In [26]:
print(df.loc[0,'clean_text'])

me spam is the tool for dissident news since the fact that its unsolicited means that recipients cant be blamed for being on a mailing list russell turpin that depends on how the list is collected or even on what the senders say about how the list is collected better to just put it on a website and that way it can be surfed anonymously and it doesnt clutter my inbox it doesnt work that way a website is opt in spam is no opt if you visit a samizdat site you can get in trouble if you get samizdat spam the worst that can be said is that you might have read it and as long as the mailers send to individuals who clearly didnt opt in like party officials then other recipients cant get in trouble for requesting the mail plus its much harder to block spam than web sites but this shouldnt come as a surprize spam is speech it may be sleazy but so what lucas http xent com mailman listinfo fork

## Removing Extra Spaces :

In [27]:
def remove_extra_spaces(text):
    return re.sub(r'\s+', ' ', text).strip()

In [28]:
df['clean_text'] = df['clean_text'].apply(remove_extra_spaces)

In [29]:
df['clean_text'].iloc[0]

'me spam is the tool for dissident news since the fact that its unsolicited means that recipients cant be blamed for being on a mailing list russell turpin that depends on how the list is collected or even on what the senders say about how the list is collected better to just put it on a website and that way it can be surfed anonymously and it doesnt clutter my inbox it doesnt work that way a website is opt in spam is no opt if you visit a samizdat site you can get in trouble if you get samizdat spam the worst that can be said is that you might have read it and as long as the mailers send to individuals who clearly didnt opt in like party officials then other recipients cant get in trouble for requesting the mail plus its much harder to block spam than web sites but this shouldnt come as a surprize spam is speech it may be sleazy but so what lucas http xent com mailman listinfo fork'

## Removing escape artifacts :

In [30]:
def remove_dataset_artifacts(text):
    text = re.sub(r'escapenumber\w*', '', text)
    text = re.sub(r'escapelong', '', text)
    return text

In [31]:
df['clean_text'] = df['clean_text'].apply(remove_dataset_artifacts)

### Again remove extra spaces caused by previous operation

In [33]:
df['clean_text'] = df['clean_text'].apply(remove_extra_spaces)

In [36]:
df['clean_text'].iloc[0]

'me spam is the tool for dissident news since the fact that its unsolicited means that recipients cant be blamed for being on a mailing list russell turpin that depends on how the list is collected or even on what the senders say about how the list is collected better to just put it on a website and that way it can be surfed anonymously and it doesnt clutter my inbox it doesnt work that way a website is opt in spam is no opt if you visit a samizdat site you can get in trouble if you get samizdat spam the worst that can be said is that you might have read it and as long as the mailers send to individuals who clearly didnt opt in like party officials then other recipients cant get in trouble for requesting the mail plus its much harder to block spam than web sites but this shouldnt come as a surprize spam is speech it may be sleazy but so what lucas http xent com mailman listinfo fork'

## Stopword Removal : (eg : is , the , etc ...)

In [37]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def remove_stopwords(text):
    words = text.split()
    words = [word for word in words if word not in ENGLISH_STOP_WORDS]
    return ' '.join(words)

In [38]:
df['clean_text'] = df['clean_text'].apply(remove_stopwords)

In [39]:
df['clean_text'].iloc[0]

'spam tool dissident news fact unsolicited means recipients blamed mailing list russell turpin depends list collected senders say list collected better just website way surfed anonymously doesnt clutter inbox doesnt work way website opt spam opt visit samizdat site trouble samizdat spam worst said read long mailers send individuals clearly didnt opt like party officials recipients trouble requesting mail plus harder block spam web sites shouldnt come surprize spam speech sleazy lucas http xent com mailman listinfo fork'

## NLP :

## TF-IDF VECTORIZER :

### Unique values / variables :

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['clean_text'])

X.shape

(5640, 52384)

### Target

In [41]:
y = df['label']

### saving the model and processed data :

In [42]:
import pickle

with open(r"C:\Users\91882\Desktop\AI-Based Email Spam Detection\model\tfidf_vectorizer.pkl", "wb") as file:
    pickle.dump(tfidf, file)

In [43]:
with open(r"C:\Users\91882\Desktop\AI-Based Email Spam Detection\model\processed_data.pkl", "wb") as file:
    pickle.dump((X, y), file)